-- Seed gerado a partir de public/dados/*.json — dados ilustrativos.

insert into public.cidades (slug,nome,uf,regiao,descricao,imagem_url,site_prefeitura) values
('jaragua-do-sul','Jaraguá do Sul','SC','Norte de Santa Catarina','Cidade de forte colonização alemã e italiana no Vale do Itapocu, conhecida pelo parque fabril, pelo empreendedorismo e por festas tradicionais como a Schützenfest, que celebra o tiro esportivo, a dança e a gastronomia germânica.','/img/cidades/jaragua-do-sul.svg','https://www.jaraguadosul.sc.gov.br'),
('blumenau','Blumenau','SC','Vale do Itajaí','Fundada por imigrantes alemães em 1850, Blumenau mantém viva a arquitetura enxaimel, a produção de cervejas artesanais e a Oktoberfest, uma das maiores festas populares do país.','/img/cidades/blumenau.svg','https://www.blumenau.sc.gov.br'),
('florianopolis','Florianópolis','SC','Grande Florianópolis','Capital de Santa Catarina, a Ilha da Magia reúne cultura açoriana, praias, o boi de mamão, a renda de bilro e uma cena vibrante de música, tecnologia e economia criativa.','/img/cidades/florianopolis.svg','https://www.pmf.sc.gov.br'),
('joinville','Joinville','SC','Norte de Santa Catarina','Maior cidade catarinense, a Cidade das Flores e das Bicicletas é polo industrial e sede do Festival de Dança de Joinville, o maior do mundo em número de participantes.','/img/cidades/joinville.svg','https://www.joinville.sc.gov.br'),
('curitiba','Curitiba','PR','Região Metropolitana de Curitiba','Capital do Paraná, referência em planejamento urbano, parques, teatros e uma agenda cultural intensa que mistura tradições de imigrantes europeus, ucranianos e a cultura paranaense.','/img/cidades/curitiba.svg','https://www.curitiba.pr.gov.br'),
('ipatinga','Ipatinga','MG','Vale do Aço — Minas Gerais','Coração do Vale do Aço mineiro, Ipatinga cresceu ao redor da siderurgia e hoje se destaca pelo Parque Ipanema, por feiras de economia criativa e por uma agenda cultural que valoriza a identidade do interior de Minas.','/img/cidades/ipatinga.svg','https://www.ipatinga.mg.gov.br')
on conflict (slug) do nothing;

insert into public.eventos (titulo,descricao,descricao_completa,categoria,cidade,cidade_nome,uf,local,endereco,data_inicio,data_fim,horario,entrada,preco_texto,imagem_url,link_oficial,organizador_nome,status,criado_em) values
('34ª Schützenfest','A tradicional festa do tiro esportivo, da dança e da gastronomia germânica de Jaraguá do Sul, com desfiles, bandinhas típicas e concursos de tiro ao alvo.','A Schützenfest resgata a cultura das sociedades de tiro trazidas pelos imigrantes alemães. São dez dias de programação com desfile de abertura, apresentações de grupos folclóricos, praça de alimentação típica (marreco, eisbein, chucrute e cucas), chopp artesanal e o concurso que elege o Rei e a Rainha do Tiro. Entrada gratuita em vários dias; consulte a tabela oficial.','cultura','jaragua-do-sul','Jaraguá do Sul','SC','Parque Municipal de Eventos','Rua Prefeito Waldemar Grubba, 1447 - Vila Baependi','2026-10-08','2026-10-18','A partir das 18h nos dias úteis; a partir das 12h aos finais de semana','misto','Gratuito em vários dias; ingressos de R$ 10 a R$ 20 nos demais','/img/1122.png','https://www.jaraguadosul.sc.gov.br','Prefeitura de Jaraguá do Sul','aprovado','2026-08-01T12:00:00.000Z'),
('Novale Experience 2026','O maior evento de inovação e empreendedorismo do Norte catarinense, com palestras, rodadas de negócios e imersão em tecnologias emergentes.','Promovido pela Prefeitura de Jaraguá do Sul e pelo Centro de Inovação, o Novale Experience reúne startups, investidores, indústria e poder público em dois dias de programação. Inclui trilhas de inteligência artificial, indústria 4.0, economia criativa e uma feira de expositores com pequenos negócios locais.','negocios','jaragua-do-sul','Jaraguá do Sul','SC','Centro de Inovação de Jaraguá do Sul','Rua Reinoldo Rau, 61 - Centro','2026-11-21','2026-11-22','9h às 19h','gratuito','Gratuito mediante inscrição prévia','/img/novale.png','https://www.sympla.com.br','Centro de Inovação de Jaraguá do Sul','aprovado','2026-08-02T12:00:00.000Z'),
('Fashion Tech: inovar, capacitar e proteger ideias na moda','Palestra sobre como a tecnologia transforma o setor da moda, da criação de produtos à proteção da propriedade intelectual.','Encontro voltado a empreendedores e profissionais criativos que querem entender como incorporar tecnologia ao desenvolvimento de produtos de moda, quais competências o mercado exige e como proteger criações originais. Inclui espaço de networking com marcas autorais da região.','educacao','jaragua-do-sul','Jaraguá do Sul','SC','Centro de Inovação (Novale)','Rua Reinoldo Rau, 61 - Centro','2026-11-13','2026-11-13','19h','pago','R$ 30','/img/fashiontech.png','https://www.sympla.com.br','Novale','aprovado','2026-08-03T12:00:00.000Z'),
('Treinamento Casa Inteligente','Capacitação prática sobre automação residencial: segurança, conforto e eficiência energética com tecnologia acessível.','Voltado a instaladores, revendas e curiosos, o treinamento mostra como integrar câmeras, fechaduras, iluminação e sensores em uma residência conectada. Traz noções de projeto, orçamento e manutenção, com demonstração ao vivo.','educacao','jaragua-do-sul','Jaraguá do Sul','SC','Auditório Discefone','Av. Getúlio Vargas, 300 - Centro','2026-10-22','2026-10-22','14h às 18h','gratuito','Gratuito com inscrição','/img/intelbrass.png','https://www.sympla.com.br','Discefone','aprovado','2026-08-04T12:00:00.000Z'),
('Curso de Oratória — Turma de Verão','Aprenda a se expressar com clareza e confiança em apresentações, reuniões e no dia a dia.','Curso intensivo de comunicação e expressão para quem quer perder o medo de falar em público. Aborda estrutura de discurso, respiração, linguagem corporal e uso da voz, com exercícios práticos gravados em vídeo para autoavaliação.','educacao','jaragua-do-sul','Jaraguá do Sul','SC','Espaço Uninter - Polo Jaraguá do Sul','Rua Jorge Czerniewicz, 99 - Czerniewicz','2027-01-18','2027-01-20','19h às 22h','pago','R$ 120','/img/oratoria.jpg','https://www.sympla.com.br','Coletivo de Comunicação de Jaraguá','aprovado','2026-08-05T12:00:00.000Z'),
('Comédia Daqui — Stand-up toda quarta','O comedy club do Norte catarinense apresenta uma noite de stand-up com humoristas da região e convidados.','Toda quarta-feira o palco recebe comediantes locais testando material novo, com um headliner convidado fechando a noite. Ingressos limitados. Ambiente para maiores de 16 anos.','cultura','jaragua-do-sul','Jaraguá do Sul','SC','Tobatta Comedy Club','Rua Epitácio Pessoa, 415 - Centro','2026-09-30','2026-09-30','20h','pago','R$ 25','/img/comedia.jpg','https://www.sympla.com.br','Tobatta Comedy','aprovado','2026-08-06T12:00:00.000Z'),
('Oktoberfest Blumenau 2026','A segunda maior festa alemã do mundo: desfiles, bandinhas, chopp em metro e a tradicional dança dos tamancos.','Durante 18 dias, o Parque Vila Germânica recebe a Oktoberfest com pavilhões temáticos, concurso do chopp em metro, desfiles pelas ruas do centro e apresentações de grupos folclóricos. A festa movimenta hotelaria, comércio e centenas de trabalhadores temporários da cidade.','gastronomia','blumenau','Blumenau','SC','Parque Vila Germânica','Rua Alberto Stein, 199 - Velha','2026-10-07','2026-10-25','A partir das 17h nos dias úteis; a partir das 11h aos fins de semana','pago','A partir de R$ 20; gratuito para crianças até 12 anos','/img/chiseta.jpg','https://www.vilagermanica.com.br','Fundação Vila Germânica','aprovado','2026-08-07T12:00:00.000Z'),
('Festival de Dança de Joinville 2027','O maior festival de dança do mundo em número de participantes, com mostras competitivas, oficinas e apresentações gratuitas na rua.','Reconhecido pelo Guinness Book, o festival reúne milhares de bailarinos de todo o país em ballet clássico, dança contemporânea, jazz, sapateado e danças urbanas. Além das mostras no Centreventos, há o Palco Aberto, com apresentações gratuitas em praças e na Rua das Palmeiras.','cultura','joinville','Joinville','SC','Centreventos Cau Hansen','Av. José Vieira, 315 - Saguaçu','2027-04-20','2027-04-30','Mostras a partir das 19h; Palco Aberto durante o dia','misto','Palco Aberto gratuito; mostras no teatro a partir de R$ 30','/img/oratoria.jpg','https://www.festivaldedanca.com.br','Instituto Festival de Dança de Joinville','aprovado','2026-08-08T12:00:00.000Z'),
('Natal de Curitiba — Programação nos Parques','Corais, espetáculos de luz e feiras de artesanato espalhados pelos parques e pela ópera de arame.','A programação natalina de Curitiba ocupa o Parque Barigui, o Jardim Botânico e a Ópera de Arame com apresentações gratuitas de corais, projeções, presépios e a Feira de Artesanato de Natal, que reúne produtores da região metropolitana.','cultura','curitiba','Curitiba','PR','Parques e espaços culturais da cidade','Vários locais - consulte a programação oficial','2026-12-01','2026-12-23','Apresentações às 20h; feiras a partir das 10h','gratuito','Gratuito','/img/jaragua-do-sul-vista-de-cima.jpg','https://www.curitiba.pr.gov.br','Fundação Cultural de Curitiba','aprovado','2026-08-09T12:00:00.000Z'),
('Mostra de Boi de Mamão e Cultura Açoriana','Apresentações do folguedo tradicional da Ilha, com oficinas de confecção de bonecos e roda de conversa sobre a cultura açoriana.','Encontro de grupos de boi de mamão das comunidades do Ribeirão da Ilha, Santo Antônio de Lisboa e Pântano do Sul. Além das apresentações, há oficinas para crianças, feira de produtores da maricultura e apresentação de cantoria de terno de reis.','cultura','florianopolis','Florianópolis','SC','Largo da Alfândega','Centro - Florianópolis','2026-11-08','2026-11-09','10h às 18h','gratuito','Gratuito','/img/jaragua-do-sul-vista-de-cima.jpg','https://www.pmf.sc.gov.br','Fundação Cultural de Florianópolis Franklin Cascaes','aprovado','2026-08-10T12:00:00.000Z'),
('Feira de Economia Criativa no Parque Ipanema','Feira mensal de artesãos, produtores de alimentos e food trucks no principal cartão-postal de Ipatinga.','Todo segundo domingo do mês, o Parque Ipanema recebe cerca de 120 expositores de artesanato, moda autoral, plantas, gastronomia e produtos agroecológicos do Vale do Aço. Há programação musical com artistas locais e espaço kids.','comunitario','ipatinga','Ipatinga','MG','Parque Ipanema','Av. Pedro Linhares Gomes - Horto','2026-10-11','2026-10-11','9h às 16h','gratuito','Gratuito','/img/PARQUE-IPANEMA-FECHADA-scaled.jpg','https://www.ipatinga.mg.gov.br','Secretaria de Cultura, Esporte e Lazer de Ipatinga','aprovado','2026-08-11T12:00:00.000Z'),
('Corrida de Rua Vale do Aço','Prova de 5 km e 10 km pelas avenidas de Ipatinga, com percurso passando pelo Parque Ipanema.','Circuito de corrida de rua com largada no Centro e chegada no Parque Ipanema. Categorias por faixa etária, kit atleta com camiseta e medalha, e prova kids sem cronometragem. Parte da renda é destinada a projetos sociais esportivos da cidade.','esporte','ipatinga','Ipatinga','MG','Largada na Praça 1º de Maio','Centro - Ipatinga','2026-11-15','2026-11-15','6h30 (largada)','pago','R$ 90 (lote promocional)','/img/ipatinga-parque-ipanema.jpg','https://www.ipatinga.mg.gov.br','Liga de Atletismo do Vale do Aço','aprovado','2026-08-12T12:00:00.000Z');
